Sprint 17. DI-Koin implementation.
ovseychik/PlaylistMaker pull request #18
Opened 2023-08-06 14:09 UTC by ovseychik

Dependency injection sprint.

2023-08-10 06:51 UTC, DmitrijEgorow requested changes

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/data/network/RetrofitNetworkClient.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Сейчас minSdk = 21, а этот метод требует api = 23
Что будет происходить на устройствах с api = 21, 22?
Можно либо поднять minSdk (тогда эта аннтоация станет не нужна), либо сделать другой метод для устройств с низкой версией (обычно некоторая заглушка, которая сообщит о том, что эти возможности на устройстве не поддерживаются)

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/ui/viewmodel/SearchViewModel.kt
>      fun searchTrack(newSearchText: String) {
Точно для получения строкового ресурса нужен именно application:` getApplication<Application>()`?

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/data/impl/TrackRepositoryImpl.kt
В одном случае Resource.Error(R.string...), а в другом Resource.Error("...")
Аккуратнее с захардкоженными строками

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/settings/data/impl/SettingsRepositoryImpl.kt
> +    )*/
Если этот код больше не нужен, то можно смело удалять – вся история изменений хранится в github

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/activity/PlayerActivity.kt
Вместо `binding.apply { ... }`
можно использовать `with(.)`
```
with(binding) {
     currentTime.text = millisFormat(track)
     // something else
}
```

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
Мне понравилось, как общий по логике код выделен в функции show__()

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/di/DataModule.kt
> +            .baseUrl("https://itunes.apple.com")
Можно вынести в константу

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/data/device_storage/SearchHistorySharedPrefs.kt
>  package com.example.playlistmaker.search.data.device_storage
Для пакетов обычно не используют подчеркивания
Подробнее про стиль можно прочитать в [документации](https://kotlinlang.org/docs/coding-conventions.html#naming-rules)

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/activity/PlayerActivity.kt
Картинка явно не с тем разрешением, которое нужно

![Screenshot_20230810_123607](https://github.com/ovseychik/PlaylistMaker/assets/36837067/fc760f25-ef79-4816-a9cb-ebec6a34dd4b)

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
На кнопке должен был быть текст

![Screenshot_20230810_124234](https://github.com/ovseychik/PlaylistMaker/assets/36837067/3ba900d5-25e9-48a0-bea4-f85c215bd0ec)

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
У меня не показывается ProgressBar


https://github.com/ovseychik/PlaylistMaker/assets/36837067/30e288fd-6f0d-49fd-afdd-85605ef0b19b

2023-08-10 06:51 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/data/impl/PlayerRepositoryImpl.kt
>          mediaPlayer.setDataSource(url)
При любой смене конфигурации (например, unfolding / открытие в режиме плавающего окна / разделённого экрана) и активном воспроизведении композиции приложение вылетает с 
```
Caused by: java.lang.IllegalStateException
at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1212)
at com.example.playlistmaker.player.data.impl.PlayerRepositoryImpl.preparePlayer(PlayerRepositoryImpl.kt:11)
at com.example.playlistmaker.player.domain.impl.PlayerInteractorImpl.preparePlayer(PlayerInteractorImpl.kt:10)
at com.example.playlistmaker.player.ui.viewmodel.PlayerViewModel.preparePlayer(PlayerViewModel.kt:25)
```



https://github.com/ovseychik/PlaylistMaker/assets/36837067/52f0eb56-1ab7-42ee-9037-c138da184160

2023-08-10 11:51 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
Поправил, текст вернулся. Немного топорно, но пока такая кнопка одна

2023-08-10 11:51 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/player/ui/activity/PlayerActivity.kt
Исправлено

2023-08-10 11:51 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/data/device_storage/SearchHistorySharedPrefs.kt
>  package com.example.playlistmaker.search.data.device_storage
Чтобы в рамках ревью не двигать файлы (с точки зрения гита удаление и создание), поправлю после приёмки ДЗ. Принято.

2023-08-10 11:52 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/di/DataModule.kt
> +            .baseUrl("https://itunes.apple.com")
Вынес.

2023-08-10 11:53 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
Спасибо

2023-08-10 11:54 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/player/ui/activity/PlayerActivity.kt
Поправил. Спасибо!

2023-08-10 11:54 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/settings/data/impl/SettingsRepositoryImpl.kt
> +    )*/
Не заметил его. Поправил.

2023-08-10 11:54 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/data/impl/TrackRepositoryImpl.kt
Поправил.

2023-08-10 11:55 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/ui/viewmodel/SearchViewModel.kt
>      fun searchTrack(newSearchText: String) {
Да, перебор. Упростил, спасибо!

2023-08-11 09:01 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
Подозрительно. У меня есть. Это Samsung OneUI? 

https://github.com/ovseychik/PlaylistMaker/assets/5370490/c3fac723-4e92-455d-b81a-21c885a602b8

2023-08-11 09:44 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/ui/activity/SearchActivity.kt
Да, Samsung OneUI

2023-08-13 14:30 UTC, ovseychik commented
Исправлена обложка в плеере. Добавлена проверка, что есть трек при создании активити плеера.

2023-08-14 13:09 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/domain/impl/TrackInteractorImpl.kt
>  class TrackInteractorImpl(private val repository: TrackRepository) : TrackInteractor {
Приложение вылетает с NPE при успешном поиске:
```
FATAL EXCEPTION: pool-3-thread-1 Process: com.example.playlistmaker, PID: 4957 java.lang.NullPointerException: Parameter specified as non-null is null: method com.example.playlistmaker.search.domain.model.Track., parameter previewUrl 
at com.example.playlistmaker.search.domain.model.Track.(Unknown Source:42) 
at com.example.playlistmaker.search.data.impl.TrackRepositoryImpl.searchTrack(TrackRepositoryImpl.kt:30)
at com.example.playlistmaker.search.domain.impl.TrackInteractorImpl.searchTrack$lambda$0(TrackInteractorImpl.kt:15)
```



https://github.com/ovseychik/PlaylistMaker/assets/36837067/d09ebb9a-3fdf-4c59-beae-f92aec78a5aa

2023-08-20 14:15 UTC, ovseychik commented
NPE при поиске исправлен. Приложение не вылетает при изменении размера окна и воспроизведении. 

https://github.com/ovseychik/PlaylistMaker/assets/5370490/ccedb94f-4676-463c-9704-35fea6ee16f6

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/data/impl/PlayerRepositoryImpl.kt
> +    override fun getPlayer(): MediaPlayer {
Зачем этот метод? Вроде нигде не используется. Напомню, что все зависимости для работы компонентов передаются через конструктор.

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/domain/impl/TrackInteractorImpl.kt
Приложение вылетает с NPE, если ввести, например, строку "abcd"

```
FATAL EXCEPTION: pool-4-thread-1 
Process: com.example.playlistmaker, PID: 23605 java.lang.NullPointerException: Parameter specified as non-null is null: method com.example.playlistmaker.search.domain.model.Track., parameter releaseDate 
at com.example.playlistmaker.search.domain.model.Track.(Unknown Source:27) 
at com.example.playlistmaker.search.data.impl.TrackRepositoryImpl.searchTrack(TrackRepositoryImpl.kt:30) 
at com.example.playlistmaker.search.domain.impl.TrackInteractorImpl.searchTrack$lambda$0(TrackInteractorImpl.kt:15)
```


https://github.com/ovseychik/PlaylistMaker/assets/36837067/94f8b4fe-e550-4d81-b6ec-a82a102a39e6

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/activity/PlayerActivity.kt
При возврате назад с экрана аудиоплеера (важно, что пользователь вручную не останавливал воспроизведение отрывка), а потом при переходе на экран аудиоплеера с любым треком кнопка воспроизведения не работает, воспроизведение трека не запускается

https://github.com/ovseychik/PlaylistMaker/assets/36837067/9609ff0e-886c-43c2-aa2a-59cb677bf430

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/ui/viewmodel/PlayerViewModel.kt
>      fun controlPlayerState() {
Приложение вылетает с `IllegalStateException` при следующем сценарии: на экране аудиоплеера пользователь запускает воспроизведение, вручную останавливает его до конца отрывка, уходит с экрана, затем опять переходит на экран аудиоплеера и пытается запустить воспроизведение. 

```
FATAL EXCEPTION: main
Process: com.example.playlistmaker, PID: 15633
java.lang.IllegalStateException
at android.media.MediaPlayer._start(Native Method)
at android.media.MediaPlayer.startImpl(MediaPlayer.java:1508)
at android.media.MediaPlayer.start(MediaPlayer.java:1472)
at com.example.playlistmaker.player.data.impl.PlayerRepositoryImpl.startPlayer(PlayerRepositoryImpl.kt:28)
at com.example.playlistmaker.player.data.impl.PlayerRepositoryImpl.controlPlayerState(PlayerRepositoryImpl.kt:58)
at com.example.playlistmaker.player.domain.impl.PlayerInteractorImpl.controlPlayerState(PlayerInteractorImpl.kt:30)
at com.example.playlistmaker.player.ui.viewmodel.PlayerViewModel.controlPlayerState(PlayerViewModel.kt:50)

```


https://github.com/ovseychik/PlaylistMaker/assets/36837067/9fe79809-1115-4864-84a6-ebff39ce104f

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/data/impl/PlayerRepositoryImpl.kt
> +        } catch (e: IllegalStateException) {
Лучше продумать, что необходимо делать при жц компонентов.

2023-08-21 08:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/player/domain/PlayerRepository.kt
> +*/
Стоит удалять закомментированный код

2023-10-09 15:32 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/player/data/impl/PlayerRepositoryImpl.kt
> +    override fun getPlayer(): MediaPlayer {
Убрал. Думал проверять факт наличия созданного плеера

2023-10-09 15:33 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/search/domain/impl/TrackInteractorImpl.kt
Не прилетало одно из полей в response. Добавил признак нуллабельности (?)

2023-10-09 15:34 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/player/domain/PlayerRepository.kt
> +*/
Убрал

2023-10-09 15:36 UTC, ovseychik commented on app/src/main/java/com/example/playlistmaker/player/ui/viewmodel/PlayerViewModel.kt
>      fun controlPlayerState() {
Исправлено. У меня плеер существовал в виде синглтона вместо фабрики. Из-за чего была попытка повторно инициализировать ранее использованный плеер, что нельзя делать (RTFM официальную документацию 😅).
Спасибо наставнику

2023-10-09 15:39 UTC, ovseychik commented
Учтены комментарии ревьюера. Плеер теперь не крашится при воспроизведении нового трека (в repository и interactor module это теперь фабрика вместо сингла).

2023-10-10 21:56 UTC, DmitrijEgorow commented
При сворачивании/разворачивании приложения кнопка Play и прогресс отражают некорректное текущее состояние воспроизведения


https://github.com/ovseychik/PlaylistMaker/assets/36837067/25c7f2ee-cbc6-4905-bf51-a4b1141185ad

2023-10-10 22:03 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/search/data/network/RetrofitNetworkClient.kt
> +                Log.e("RetrofitNetworkClient", "User is below Android M, skipping network check. Advise to upgrade.") //At least we don't break the app.
Точно уровень логирования error?

2023-10-10 22:04 UTC, DmitrijEgorow commented
Студия подсказывает [Package directive does not match the file location ](https://github.com/ovseychik/PlaylistMaker/blob/6db3108b5d646fce512f9a60367290cd79f089dc/app/src/main/java/com/example/playlistmaker/player/data/dto/TrackForPlayer.kt#L1)

2023-10-11 00:45 UTC, merged